### ISSUE TITLE
Is it possible to modify cocacola and peisicola files in the cola-pod

### ISSUE THREAD

**Issue by JohnsonOUO** [joyme123/cola-device-plugin#1]
By your test. There are two resources /etc/colas/cocacola and /etc/colas/peisicola.
Can I find these two file or get any information about these two files in the cola-pod ?
If it can, when I change files in cola-pod, the file in /etc/colas/* are changed too ?  
Thanks !

**Comment by joyme123** [comment]
these two files are only used to mock as devices. 

As files, you can mount parent directory into pod to use these two files.
